#!/bin/bash
# Quick connection script for Termux

echo "================================================"
echo "Railway VPS SSH Connection Guide for Termux"
echo "================================================"
echo ""
echo "1. First, install OpenSSH in Termux:"
echo "   pkg update && pkg upgrade"
echo "   pkg install openssh"
echo ""
echo "2. Get your Railway deployment URL from:"
echo "   https://railway.app/dashboard"
echo "   Make sure TCP Proxy is enabled in service settings"
echo ""
echo "3. Use this command to connect:"
echo ""
echo "ssh root@YOUR_RAILWAY_URL"
echo ""
echo "If Railway assigns a custom port:"
echo "ssh -p PORT root@YOUR_RAILWAY_URL"
echo ""
echo "Replace YOUR_RAILWAY_URL with your actual Railway domain"
echo "Replace PORT with the assigned port (if not 22)"
echo ""
echo "================================================"
echo "Optional: Set up SSH Key Authentication"
echo "================================================"
echo ""
echo "1. Generate SSH key in Termux:"
echo "   ssh-keygen -t ed25519"
echo ""
echo "2. Copy public key to VPS:"
echo "   ssh-copy-id root@YOUR_RAILWAY_URL"
echo ""
echo "3. Or manually copy:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   # Then on VPS:"
echo "   echo 'PASTE_PUBLIC_KEY_HERE' >> ~/.ssh/authorized_keys"
echo ""
echo "4. Connect without password:"
echo "   ssh root@YOUR_RAILWAY_URL"
echo ""
echo "================================================"
echo "Common SSH Options"
echo "================================================"
echo ""
echo "Verbose mode (for debugging):"
echo "ssh -v root@YOUR_RAILWAY_URL"
echo ""
echo "Keep connection alive:"
echo "ssh -o ServerAliveInterval=60 root@YOUR_RAILWAY_URL"
echo ""
echo "Forward local port to VPS:"
echo "ssh -L 8080:localhost:80 root@YOUR_RAILWAY_URL"
echo ""
echo "Forward VPS port to local:"
echo "ssh -R 8080:localhost:3000 root@YOUR_RAILWAY_URL"
echo ""
echo "================================================"
echo "File Transfer with SCP"
echo "================================================"
echo ""
echo "Upload file to VPS:"
echo "scp file.txt root@YOUR_RAILWAY_URL:/root/"
echo ""
echo "Download file from VPS:"
echo "scp root@YOUR_RAILWAY_URL:/root/file.txt ./"
echo ""
echo "Upload directory:"
echo "scp -r directory/ root@YOUR_RAILWAY_URL:/root/"
echo ""
echo "================================================"
